### ISSUE TITLE
Static Weather Strings

### ISSUE THREAD

**Issue by Gnossos** [willasm/obsidian-open-weather#17]
This is really a question.

But before I ask, thanks for the fantastic plugin. And the documentation is fantastic too. It took me less than 1/2 hour to add the weather to a navigation bar I'm designing for my daily notes. From installation to implementation, this must be a record time for me. Well designed and well done!

Now my question. For Daily Notes, once the current day is over, I'd rather have a field with the static weather (i.e., what the weather was like on that day) than a continually updated report on the current weather. But while the date of the daily note is today's date, I'd prefer to have the weather updated regularly. Is there any way to do this?

Oh, and BTW: change the documentation. Obsidian no longer uses "cssclass." It's now "cssclasses."

**Comment by willasm** [comment]
First thank you for the compliment, that really means a lot to me and is appreciated. I have actually been meaning to update the example.md for a while as my daily template has changed a fair bit since I wrote that. Still I'm glad the documentation was helpful to you.

As for your idea, I really like that and would prefer that myself. That would be easy enough to do with javascript but Obidian does not allow script inside of notes. I would need to find a way to run a script every time a daily note is opened. That might take me a while to figure that out. Templater will run a script, but I would like to find a way to automate this, otherwise the script would have to be run manually on older daily notes.

How are you using this feature anyways? Are you using a similar method to the example file with `<div class="weather_historical_3">%weather3%</div>` and `<div class="weather_current_4"></div>`. For the older notes it is simply a matter of removing the line with `<div class="weather_current_4"></div>` to stop displaying the current weather. That is basically just one line of code. Please, if you can show me a sample of how you have this setup in your template then I can see what needs to be done to get this to work for you in particular. I know Templater does have an option to run a script on templater startup, that may be useful in this situation.

I will look into this as I would like to apply this to my template as well, William.

ps: Thanks for the info on cssclasses. I was not aware of that and I did a search to find that was changed in v1.4 Never would have known if you had not pointed that out. "tag" "alias" were also changed to "tags" and "aliases".

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

Thank you, William McKeever
