### ISSUE TITLE
Working in the mobile version

### ISSUE THREAD

**Issue by maksim77** [willasm/obsidian-open-weather#2]
Thank you so much for the plugin! 
Is it possible for it to work on mobile devices? I often create my daily notes from my mobile even before I get to my laptop. It would be great if meta information about the weather was put down at this moment...

**Comment by willasm** [comment]
The only reason I have it disabled is because it uses the statusbar to display the current weather which the mobile version does not support. I don't actually have the mobile version installed but I will install it to test this.

You may be able to get to work on mobile by editing the `manifest.json` and setting `"isDesktopOnly": true` to `"isDesktopOnly": false` then disabling the statusbar in OpenWeather plugin settings. I will try this when I have the time to install the mobile version.

**Comment by willasm** [comment]
Just tested this and it works fine. Just make the edit to the manifest and it works perfectly, although without the statusbar. I will add the change on the next update.
