### ISSUE TITLE
Dynamic Location

### ISSUE THREAD

**Issue by corbing** [willasm/obsidian-open-weather#7]
It would be great to be able to get weather from multiple locations instead of a single pre-configured location in Settings.

For example, in %weather1% I might have:
Location = New York, USA
Current Temp: %temp%° • Feels Like: %feels%°
Location = Edmonton, Canada
Current Temp: %temp%° • Feels Like: %feels%°

**Comment by willasm** [comment]
That sounds like a good idea. How many locations would you like to see? Two or three? More?
I don't think I would want too many as it might get confusing for some users that only want to use one location.
Let me know how many you would be likely to use.

I am currently planning to add an option to over ride the location setting with latitude and longitude coordinates.
As this directly involves the locations setting I want to get that working first then I'll add the option for at least one more location.

Thanks for the suggestion, William.

**Comment by corbing** [comment]
Personally, I have two locations that I would like to insert into my daily notes, but if I am traveling it might be nice to also include the weather for the current location.

The most flexible implementation would be to accept it was an argument when calling OpenWeather.  Then the user could have an unlimited number of locations.  

For example, it would be great to do something like this:

%weather1("Los Angeles, USA")%
%weather2("Mexico City, Mexico")%
%weather1("Edmonton, Canada")%

You could use the default location in settings if an argument isn't passed.

**Comment by willasm** [comment]
Sorry for not getting back to you sooner, been away for Easter. Hopefully I'll get this done this week time permitting.

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

@corbing Sorry but I never did get around to this. It would have required almost a complete re-write of the existing code in order to get this to work. However, if you are still using this plugin you will be happy to know that the new plugin includes up to 5 locations to get the weather from. I also doubled the number of templates from 4 to 8.

Thank you, William McKeever
